feat: implement positioner and new tooltip/popover/popconfirm
Yoctol/tailor-ui pull request #117
Opened 2019-03-22 15:58 UTC by jigsawye

之後的浮動元素都會用這個元件重寫，現在 lab 裡有個新的 tooltip 可以玩玩看

close #37

2019-03-22 16:11 UTC, jigsawye commented
試玩由此去: https://deploy-preview-117--tailor-ui.netlify.com/labs/tooltip

2019-03-26 07:47 UTC, tw0517tw approved these changes
不明覺厲

2019-03-26 09:33 UTC, kpman requested changes
要改一下

2019-03-26 09:33 UTC, kpman commented on packages/tailor-ui-lab/src/Popconfirm/Popconfirm.tsx
> +    const icon = getTypeIcon(type);
上面空行

2019-03-26 09:33 UTC, kpman commented on packages/tailor-ui/src/utils/useClickOutside.ts
> +export interface KeydownProps {
應該不是 KeydownProps？

2019-03-26 09:46 UTC, kpman approved these changes

2019-03-26 09:46 UTC, merged