feat(TelInput): add FormField in TelInput, ref: #311
Yoctol/tailor-ui pull request #373
Opened 2019-12-12 07:41 UTC by neighborhood999

<img width="815" alt="螢幕快照 2019-12-12 下午3 40 57" src="https://user-images.githubusercontent.com/10325111/70692234-d8516680-1cf5-11ea-8993-545efd5e1fa4.png">

2019-12-12 07:50 UTC, jigsawye commented
`TelInput.md` 裡需要加個 example
PR 可以寫個 related #311

2019-12-12 09:36 UTC, jigsawye requested changes
目前這樣無法在 validationMessage or validator 拿到 onChange value 做處理

2019-12-12 09:36 UTC, jigsawye commented on packages/tailor-ui/src/TelInput/TelInput.tsx
> +      })}
這段應該跟底下的 onPhoneNumberChange 的 onChange compose 才對

2019-12-12 09:36 UTC, jigsawye commented on packages/tailor-ui/src/TelInput/TelInput.tsx
> +        fieldId={id}
這要換成 useFormField 的 labelId

2019-12-12 09:37 UTC, neighborhood999 commented on packages/tailor-ui/src/TelInput/TelInput.tsx
> +        fieldId={id}
原先的 `id` 沒用了？

2019-12-12 09:38 UTC, jigsawye commented on packages/tailor-ui/src/TelInput/TelInput.tsx
> +        fieldId={id}
原先的 id 傳入 useFormField 後如果是 undefined 就會自動產生一個 id，否則會 return 傳入的 id

2019-12-12 09:46 UTC, neighborhood999 commented on packages/tailor-ui/src/TelInput/TelInput.tsx
> +      })}
不是很熟不知道是不是這樣改 😐

2019-12-12 10:56 UTC, jigsawye commented on packages/tailor-ui/src/TelInput/TelInput.tsx
> +  });
這樣改錯了


應該這樣才正確：

```jsx
    <StyledTelInput invalid={invalid}>
      <IntlTelInput
        fieldId={labelId}
        fieldName={name}
        onPhoneNumberChange={(isValid, value, phoneInfo, fullPhoneNumber) => {
          setValue(value);
          if (onChange) {
            onChange(isValid, value, phoneInfo, fullPhoneNumber);
          }
        }}
        onPhoneNumberBlur={onBlur}
        format
        preferredCountries={['tw']}
        {...props}
      />
    </StyledTelInput>
```

2019-12-12 13:07 UTC, neighborhood999 commented on packages/tailor-ui/src/TelInput/TelInput.tsx
> +  });
照上面那樣改編輯器會該該叫，所以在外面寫了一個 function 還有參數的型別，感覺這邊是不是可以寫一個 interface 之類的？TypeScript 好難不會寫

2019-12-13 02:51 UTC, jigsawye commented on packages/tailor-ui/src/TelInput/TelInput.tsx
> +  });
可以在上面寫個 ChangeHandler

```ts
type ChangeHandler = (
  isValid: boolean,
  value: string,
  phoneInfo: object,
  fullPhoneNumber: string
) => void;

interface TelInputProps {
  // ...
  onChange?: ChangeHandler;
}

// ...

const onPhoneNumberChange: ChangeHandler = (
  isValid,
  value,
  phoneInfo,
  fullPhoneNumber
) => {
  setValue(value);

  if (onChange) {
    onChange(isValid, value, phoneInfo, fullPhoneNumber);
  }
}
```

2019-12-13 03:23 UTC, neighborhood999 commented on packages/tailor-ui/src/TelInput/TelInput.tsx
> +  });
Done，讚嘆 typescript 大師

2019-12-13 03:33 UTC, jigsawye approved these changes

2019-12-13 03:34 UTC, merged