feat(trigger): auto fix placement when popup overflow
Yoctol/tailor-ui pull request #53
Opened 2019-02-01 04:32 UTC by jigsawye

寫個感覺，感覺系開發

![auto-fix-placement-trigger](https://user-images.githubusercontent.com/8567270/52102823-7d52db80-261d-11e9-8278-64576cbb9592.gif)

https://github.com/Yoctol/kurator/issues/2268

2019-02-01 04:41 UTC, jigsawye commented
補個 tooltip 的效果

![auto-fix-placement-trigger tooltip](https://user-images.githubusercontent.com/8567270/52103039-9f992900-261e-11e9-9e37-dcce07ff0785.gif)

2019-02-12 02:11 UTC, jigsawye commented
這支可以 review 了

2019-02-12 04:40 UTC, tw0517tw approved these changes

2019-02-12 14:02 UTC, chentsulin commented
可以稍微說明一下嗎，什麼時候在上面什麼時候在下面判斷依據是什麼

2019-02-12 14:59 UTC, jigsawye commented
@chentsulin 超出畫面的邊界時自動轉向

可以到 Netlify 試玩
https://deploy-preview-53--tailor-ui.netlify.com/components/dropdown
https://deploy-preview-53--tailor-ui.netlify.com/components/popover

2019-02-13 03:02 UTC, chentsulin commented
往下的不正常

2019-02-13 03:04 UTC, chentsulin requested changes
往下的不正常

2019-02-13 03:08 UTC, jigsawye commented
讓我修修

2019-02-13 03:32 UTC, jigsawye commented
@chentsulin 已修 QQ 少加上 popup element 的 height

2019-02-13 06:41 UTC, kpman approved these changes

2019-02-13 06:41 UTC, kpman commented
@chentsulin 有 requested changes

2019-02-13 08:37 UTC, merged